### ISSUE TITLE
"Call to undefined method SendinBlue\Client\Api\ListsApi::getAccount()"

### ISSUE THREAD

**Issue by NexusMTO** [vansteen/laravel-sendinblue#3]
Laravel 5.8

composer.json

"vansteen/laravel-sendinblue": "0.4"

Install provider and aliases in app.php

and copy code in Controller.

```
use Vansteen\Sendinblue\Facades\Sendinblue;

class GetResponseController extends Controller
{
 	public function index()
  {

 $config = Sendinblue::getConfiguration();
 $apiInstance = new \SendinBlue\Client\Api\ListsApi(
        // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
        // This is optional, `GuzzleHttp\Client` will be used as default.
        new \GuzzleHttp\Client(),
        $config
    );

try {
			    $result = $apiInstance->getAccount();
			    
			} catch (Exception $e) {
			    $result = 'Exception when calling AccountApi->getAccount: ';
			}


}

}
```

"Call to undefined method SendinBlue\Client\Api\ListsApi::getAccount()"

**Comment by vansteen** [comment]
Hi Carlos, I haven't be able to reproduce the problem with Laravel 5.8.37 and the package version 0.4. Did you find a solution?

**Comment by vansteen** [comment]
Hi Carlos,

According to the SendInBlue documentation, to call **getAccount()**, you should use the class  **AccountApi**

See https://github.com/sendinblue/APIv3-php-library#documentation-for-api-endpoints

You should write :  

`
$apiInstance = new \SendinBlue\Client\Api\AccountApi(
  new \GuzzleHttp\Client(),
  $config
);
`

**Comment by vansteen** [comment]
Hi Carlos,

According to the SendInBlue documentation, to call **getAccount()**, you should use the class  **AccountApi**

See https://github.com/sendinblue/APIv3-php-library#documentation-for-api-endpoints

You should write :  

`
$apiInstance = new \SendinBlue\Client\Api\AccountApi(
  new \GuzzleHttp\Client(),
  $config
);
`
